INSERT INTO PROMPTS_LANGUAGES ( LANGUAGE_ID, PROMPT_TEXT, PROMPTS_ID ) VALUES ( 
1, 'Approved By', 'APPROVED BY'); 
INSERT INTO PROMPTS_LANGUAGES ( LANGUAGE_ID, PROMPT_TEXT, PROMPTS_ID ) VALUES ( 
2, '„Ê«›ﬁ… «·„œÌ—', 'APPROVED BY'); 
INSERT INTO PROMPTS_LANGUAGES ( LANGUAGE_ID, PROMPT_TEXT, PROMPTS_ID ) VALUES ( 
1, 'Store Keeper', 'STORE KEEPER'); 
INSERT INTO PROMPTS_LANGUAGES ( LANGUAGE_ID, PROMPT_TEXT, PROMPTS_ID ) VALUES ( 
2, '√„Ì‰ «·„Œ“‰', 'STORE KEEPER'); 
INSERT INTO PROMPTS_LANGUAGES ( LANGUAGE_ID, PROMPT_TEXT, PROMPTS_ID ) VALUES ( 
1, 'Checked By', 'CHECKED BY'); 
INSERT INTO PROMPTS_LANGUAGES ( LANGUAGE_ID, PROMPT_TEXT, PROMPTS_ID ) VALUES ( 
2, '›Õ’ »Ê«”ÿ…', 'CHECKED BY'); 
commit;
 
