UPDATE PROMPTS_LANGUAGES
SET PROMPT_TEXT = '«·„œÌ— «·„«·Ì'
WHERE PROMPTS_ID = 'FINANCIAL MANAGER'
AND LANGUAGE_ID = 2;
COMMIT;
--
UPDATE PROMPTS_LANGUAGES
SET PROMPT_TEXT = '„œÌ— «·Õ”«»« '
WHERE PROMPTS_ID = 'CHEIF ACCOUNTANT'
AND LANGUAGE_ID = 2;
COMMIT;
--
UPDATE PROMPTS_LANGUAGES
SET PROMPT_TEXT = '«·„Õ«”»'
WHERE PROMPTS_ID = 'ACCOUNTANT'
AND LANGUAGE_ID = 2;
COMMIT;
