INSERT INTO FUNCTIONS ( FUNCTION_ID, FUNCTION_CODE, FUNCTION_TYPE, PRIMARY_NAME, SECONDARY_NAME,
MODULE_ID, MENU_NAME, DEVELOPED_BY, FUNCTION_VISIBLE, FUNCTION_INSERT, FUNCTION_UPDATE,
FUNCTION_DELETE, FUNCTION_PRINT, PRIMARY_DESCRIPTION, SECONDARY_DESCRIPTION, WORKFLOW, MOBILE_ORDER,
PRIMARY_NAME_MOBILE, SECONDARY_NAME_MOBILE, FUNCTION_ID_MOBILE, MOBILE_ICON, FUNCTION_CATEGORY,
FUNCTION_ORDER, FUNCTION_SUB_CATEGORY ) VALUES ( 
202221, 'SAL_R_256', 1, 'Sales Coupons Report', ' ﬁ—Ì— «·ﬂÊ»Ê‰«  «·„»«⁄… ', 6, 'SAL_M_004'
, 'fathy', 1, 1, 1, 1, 1, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, 40, NULL, NULL); 
INSERT INTO FUNCTIONS ( FUNCTION_ID, FUNCTION_CODE, FUNCTION_TYPE, PRIMARY_NAME, SECONDARY_NAME,
MODULE_ID, MENU_NAME, DEVELOPED_BY, FUNCTION_VISIBLE, FUNCTION_INSERT, FUNCTION_UPDATE,
FUNCTION_DELETE, FUNCTION_PRINT, PRIMARY_DESCRIPTION, SECONDARY_DESCRIPTION, WORKFLOW, MOBILE_ORDER,
PRIMARY_NAME_MOBILE, SECONDARY_NAME_MOBILE, FUNCTION_ID_MOBILE, MOBILE_ICON, FUNCTION_CATEGORY,
FUNCTION_ORDER, FUNCTION_SUB_CATEGORY ) VALUES ( 
202222, 'SAL_R_256_R', 2, 'Sales Coupon Reports', ' ﬁ—Ì— ﬂÊ»Ê‰«  «·„»Ì⁄« ', 6, '--'
, 'fathy', 1, 1, 1, 1, 1, NULL, NULL, 2, NULL, NULL, ' ﬁ—Ì—  ›’Ì·Ï ··«’‰«› «·„‘ —«Â'
, NULL, NULL, NULL, NULL, NULL); 
commit;
 
