INSERT INTO CODES_SYS ( CODES_SYS_ID, PRIMARY_NAME, SECONDARY_NAME, CODE_TYPES_ID,
PARENT_CODES_SYS_ID, PARENT_CODE_TYPES_ID, VISIBLE, ORDER_BY ) VALUES ( 
1, 'Sold', '„»«⁄', 950, NULL, NULL, 1, NULL); 
INSERT INTO CODES_SYS ( CODES_SYS_ID, PRIMARY_NAME, SECONDARY_NAME, CODE_TYPES_ID,
PARENT_CODES_SYS_ID, PARENT_CODE_TYPES_ID, VISIBLE, ORDER_BY ) VALUES ( 
2, 'Un Sold', '€Ì— „»«⁄', 950, NULL, NULL, 1, NULL); 
INSERT INTO CODES_SYS ( CODES_SYS_ID, PRIMARY_NAME, SECONDARY_NAME, CODE_TYPES_ID,
PARENT_CODES_SYS_ID, PARENT_CODE_TYPES_ID, VISIBLE, ORDER_BY ) VALUES ( 
3, 'All', '«·ﬂ·', 950, NULL, NULL, 1, NULL); 
commit;
 
