INSERT INTO CODE_TYPES ( CODE_TYPES_ID, PRIMARY_NAME, SECONDARY_NAME, SYSTEM_CODE_TYPE,
PARENT_CODE_TYPES_ID_REQ, SUB_SYSTEM, PARENT_CODE_TYPES_ID ) VALUES ( 
950, 'Sold / Un Sold', 'ãÈÇÚ / ÛíÑ ãÈÇÚ ', 1, 2, 1, NULL); 
commit;
 
