/*=======================================================================*/
/* 	 		   CREATED BY SAMEH NOSHI                        */
/*=======================================================================*/
CREATE TABLESPACE "BRIGHT" 
    LOGGING 
    DATAFILE 'D:\ORACLE\ORADATA\ORCL\BRIGHT.ora' SIZE 5000M AUTOEXTEND
    ON NEXT  50M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL 
    SEGMENT SPACE MANAGEMENT  AUTO;




